### ISSUE TITLE
Opportunistically track Azure SQL operations

### ISSUE THREAD

**Issue by negz** [crossplaneio/stack-azure#69]
### What problem are you facing?

CRUD operations in Azure SQL REST API are asynchronous; they [return a URL](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-async-operations) that may be polled to determine whether the requested operation has completed, and whether it was successful.

The initial implementation of the Azure MySQL and PostgreSQL controllers serialised details about these long running operations and stored them in the managed resource's status, using them to make decisions during the next reconcile. The controller has largely ignored these operations since porting to the managed resource reconciler; they are not persisted, and are consulted only once immediately after they are created. This works, but has some caveats:

* We're never quite sure if an operation is running, because there's no way to discover a running operation after it has begun. https://github.com/crossplaneio/stack-azure/pull/64#discussion_r345763687 is an example of this issue.
* We never quite sure if an operation actually succeeded.

### How could Crossplane help solve your problem?

We have a solution that works without storing and polling the running operation; I wonder if we can build on this by opportunistically storing any operation in `.status` and checking it at the next reconcile (similar to the original implementation of this controller). If no operation was recorded we'd fall back to the current behaviour. I believe this would be in compliance with API conventions:

> The status summarizes the current state of the object in the system, and is usually persisted with the object by automated processes but may be generated on the fly. At some cost and perhaps some temporary degradation in behavior, the status could be reconstructed by observation if it were lost.

```go
// Returns an Azure-AsyncOperation URL
op.PollingURL()
```

**Comment by negz** [comment]
CC @muvaf. Do you think this would make sense as a future improvement to the Azure SQL controllers?

**Comment by muvaf** [comment]
I've actually experimented with a few ideas around this. To be honest, all of them are simply hacks. Azure SDK supports creating a `Future` object only with the response of the call you originally make. So, I just ditched my changes and went for checking once since it was taking too much of my time.

Nevertheless, the user experience is bad as expected. Even though a hack, I feel like we should do it somehow. I'll try to make it by adding as minimum fields as possible, hopefully only polling URL.

**Comment by negz** [comment]
>  Azure SDK supports creating a Future object only with the response of the call you originally make.

Yeah, I noticed this too - it's unfortunate. I suspect we could probably store just the polling URL and possibly the operation kind we're trying to do (Update, Delete, etc) and use that to create a `Future`. I think the code that actually turns an `*http.Response` into a future only really cares about the operation type (which is always `Azure-AsyncOperation`), HTTP verb, and polling URL, so we may be able to do something hacky like craft an `*http.Response` from just the URL and what we know about our current lifecycle.
